### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by magistermaks** [player400/elevator#1]
- [x] Unnecessary `else` block after `continue;` on line 419.
- [x] Unnecessary `else` block after `continue;` on line 502.
- [x] Definition of `freezerdata` should use `volatile` modifier on line 262.
- [x] Functions `minimum()` and `maksimum()` should not repeat the `windy[winda]` expression.
- [x] Inconsistent naming of variables `underway_Status`, `freezerdata`, `ilewind`, `direction`, `znalezionoprzystanek`.
- [x] Unreachable statement `return false;` in function `czy_jedzie_konkretna()` on line 360
- [x] Line 512 is very long, consider splitting it to multiple `bool` variables first and then checking them in the `if()`

**Comment by mnurczynski** [comment]
Thx
